### ISSUE TITLE
[BugFix] - 기능 버그 수정

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [Team-Coverflow/Coverflow-FE#220]
## 🗺️Location
- searchResultPage.tsx
- questionWritePage.tsx
- questionDetailPage.tsx

## 🤷WHAT / WHY
- [x] 질문 등록 및 답변 등록 안됨
- [x] 기업 상세 페이지에서 뒤로 가기 버튼 클릭 시 에러 발생(뒤로 가기 버튼 클릭 시 companyList가 undefined로 찍힘)
- [ ] 기업 상세 페이지에서 뒤로 가기 버튼 클릭 시 일시적으로 '검색 결과가 없습니다' 가 보이는 문제

## ✏️HOW
- 

## ✅TODO

- [ ]
